config/routes.rb
Rails.application.routes.draw do
  root to: "users#index"
  resources :quotes #, only: [:edit]
  resources :users, only: [:index, :new, :show]
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

end

app/models/quote.rb
class Quote < ActiveRecord::Base
  belongs_to :user
  validates :user_id, :quantity, presence: true
  validates :symbol, presence: true, uniqueness: { case_sensitive: false }
  validates :quantity, :numericality => { greater_than: 0, less_than: 999999999 }

  def total_price
    self.quantity * self.price
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :quotes
  validates :email, presence: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }

  has_secure_password



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_user
    redirect_to '/login' unless current_user
  end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController

def create
  @yahoo_client = YahooFinance::Client.new
  @quote = current_user.quotes.build(quotes_params)
  @quote.symbol.upcase!
  if @yahoo_client.quotes([@quote.symbol], [:name])[0].name != "N/A"
    if @quote.save
      flash[:success] = "Акция добавлена в портфель."
      redirect_to current_user
    else
      flash[:alert] = "Ошибка"
      redirect_to current_user
    end
  else
    flash[:alert] = "Несуществующая котировка"
    redirect_to current_user
  end
end

def edit
  @quote = Quote.find_by_id(params[:id])
end

def update
  @quote = Quote.find_by_id(params[:id]).update(quotes_params)
  flash[:success] = "Successfully updated..."
  redirect_to current_user
end

def destroy
  @quote = current_user.quotes.find_by_id(params[:id]).destroy
  redirect_to current_user
end

private

def quotes_params
  params.require(:quote).permit(:symbol, :quantity)
end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_email(params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to @user
    else
      redirect_to '/login', notice: "Неверный email или пароль"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/users'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :get_price, :require_user, only: [:show]

  def index
  end

  def show
    @user = User.find(params[:id])
    @quote = Quote.new
    # @quotes = @user.quotes.all
    if @user.quotes.any?
      @chart = LazyHighCharts::HighChart.new('StockChart') do |f|
        f.title(text: 'График цены портфела')
        f.rangeSelector(selected: 1)
        f.series(name: 'Цена портфеля', data: portfolio_price)
        f.yAxis [{ title: { text: 'Цена портфеля в USD', margin: 70 } }]
        # f.legend(:align => 'right', :verticalAlign => 'top', :y => 75, :x => -50, :layout => 'vertical',)
        f.chart(defaultSeriesType: 'line')
      end
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to '/'
    else
      redirect_to '/'
    end
  end

  def portfolio_price
    @ans = Array.new(509) { 0 }
    @dates = []
    @array = []
    User.find(params[:id]).quotes.each do |q|
      @data = @yahoo_client.historical_quotes(q.symbol, start_date: Time.now - (24 * 60 * 60 * 365 * 2), end_date: Time.now)
      @data.each do |d|
        @array << d.close.to_f * q.quantity
      end
      @array.each_with_index { |e, i| @ans[i] += e }
      @array = []
    end
    @data.each { |d| @dates << d.trade_date.to_time.to_i * 1000 + 86_400_000 }
    @ans.each_with_index { |e, i| @ans[i] = [@dates[i], e] }
    @ans.reverse
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

  def get_price
    @yahoo_client = YahooFinance::Client.new
    @quotes = User.find(params[:id]).quotes.each do |q|
      q.price = @yahoo_client.quotes([q.symbol], [:ask])[0].ask.to_f
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>RubyFinance</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>
</head>

<body>


  <div class="header">
    <div class="container">


      <div class="nav pull-right">
        <% if current_user %>
          <ul>
            <li>
              <%= link_to current_user.email, @user %>
            </li>
            <li>
              <%= link_to "Log out", logout_path, method: "delete" %>
            </li>
          </ul>
          <% else %>
            <ul>
              <li>
                <%= link_to "Login", 'login' %>
                  </a>
              </li>
              <li>
                <%= link_to "Signup", 'signup' %>
                  </a>
              </li>
            </ul>
            <% end %>

      </div>
    </div>
  </div>

  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: "alert alert-info" %>
      <% end %>

        <%= yield %>

</body>

</html>

app/views/quotes/edit.html.erb
<div class="container">
  <div class="form">

  <h1>Изменить</h1>

  <%= simple_form_for(@quote) do |q| %>
    <%= q.text_field :symbol, :placeholder => "New quote symbol" %>
    <%= q.number_field :quantity, :placeholder => "New quantity", min: 1 %>
    <%= q.submit "Обновить", class: "btn-submit" %>
  <% end %>


  </div>
</div>

app/views/users/new.html.erb
<div class="login">
  <div class="container">
    <div class="form">

      <h1>Sign up</h1>

      <%= simple_form_for(@user) do |f| %>
        <%= f.text_field :name, :placeholder => "Ваше имя" %>
        <%= f.email_field :email, :placeholder => "Email" %>
        <%= f.password_field :password, :placeholder => "Пароль" %>
        <%= f.submit "Создать аккаунт", class: "btn-submit" %>
      <% end %>

    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="span8">
  <% if @user.quotes.any? %>
  <h3>Котировки в вашем портфеле (<%= @user.quotes.count %>):</h3>

  <div class="tab-pane active" id="daftar">
    <br>
    <div class="table-responsive">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Symbol</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Tota price</th>
          </tr>
        </thead>
        <% @quotes.each do |q| %>
        <tbody>
          <tr>
            <td><%=q.symbol%></td>
            <td><%=number_to_currency(q.price)%></td>
            <td><%=q.quantity%></td>
            <td><%=number_to_currency(q.total_price)%></td>
            <td><%= link_to 'Редактировать', edit_quote_path(q) %></td>
            <td><%= link_to 'Удалить', q, method: :delete %></td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
  <% end %>

</div>
<%= simple_form_for(@quote) do |f| %>
<div class="form">
  <%= f.text_field :symbol, placeholder: "Compose new quote (e.g. BAC, AAPL, QQQ, ...)" %>
  <%= f.number_field :quantity, placeholder: "Quantiy...", min: 1 %>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
</div>
<% end %>

<% if @user.quotes.any? %>
<%= high_stock("some_id", @chart) %>
<% end %>